# This file was generated by GoReleaser. DO NOT EDIT.
cask "xf-cli" do
  version "0.1.7-alpha.5"

  on_macos do
    on_intel do
      sha256 "fe5383bf38a91d62de0e15cf013983d846ed78f07fb79afe3ec446abaec1294f"
      url "https://github.com/xenforo-ltd/cli/releases/download/v#{version}/xf_macOS_amd64.tar.gz"
      rename "xf_macOS_amd64/bin/xf", "bin/xf"
    end
    on_arm do
      sha256 "c916759434760709d611ba5135d749d34aafddedab3a9ee5817f3276c1b90626"
      url "https://github.com/xenforo-ltd/cli/releases/download/v#{version}/xf_macOS_arm64.tar.gz"
      rename "xf_macOS_arm64/bin/xf", "bin/xf"
    end
  end

  on_linux do
    on_intel do
      sha256 "cea4aab56b2dc50b03515eb7654f2bb4fd21367b324b4e33a5bb57d399828e62"
      url "https://github.com/xenforo-ltd/cli/releases/download/v#{version}/xf_linux_amd64.tar.gz"
      rename "xf_linux_amd64/bin/xf", "bin/xf"
    end
    on_arm do
      sha256 "a5f8955cdef92c1e5e4581c146d6eef7eaa45dec8e8d38d5f944075184db2249"
      url "https://github.com/xenforo-ltd/cli/releases/download/v#{version}/xf_linux_arm64.tar.gz"
      rename "xf_linux_arm64/bin/xf", "bin/xf"
    end
  end

  name "xf-cli"
  desc "Command line interface for XenForo"
  homepage "https://github.com/xenforo-ltd/cli"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "bin/xf"
  generate_completions_from_executable "bin/xf", "completions",
    shell_parameter_format: :cobra,
    shells: [:bash, :zsh, :fish, :pwsh]

  zap delete: [
      "~/Library/Caches/xf/",
      "~/.cache/xf/",
    ],
    trash: [
      "~/Library/Application Support/xf/",
      "~/.config/xf/",
    ]

end
