# This file was generated by GoReleaser. DO NOT EDIT.
cask "xf-cli" do
  version "0.1.7-alpha.6"

  on_macos do
    on_intel do
      sha256 "69e4a87e9e7d3de1dac33ea9e31b22ed5aa3456500addb907068e4cc174b93e5"
      url "https://github.com/xenforo-ltd/cli/releases/download/v#{version}/xf_macOS_amd64.tar.gz"
      rename "xf_macOS_amd64/bin/xf", "bin/xf"
    end
    on_arm do
      sha256 "03a28a96c9369d4390e4ac108655e24fdba40614d1a6a6b9162a7726b625abed"
      url "https://github.com/xenforo-ltd/cli/releases/download/v#{version}/xf_macOS_arm64.tar.gz"
      rename "xf_macOS_arm64/bin/xf", "bin/xf"
    end
  end

  on_linux do
    on_intel do
      sha256 "74b5f8f577f139e111a1b379b0697c45f20e57e62a23b76643cb2f4180b3f74e"
      url "https://github.com/xenforo-ltd/cli/releases/download/v#{version}/xf_linux_amd64.tar.gz"
      rename "xf_linux_amd64/bin/xf", "bin/xf"
    end
    on_arm do
      sha256 "5877dec172c0ac33612a598df32dd55b74b5e6432cbca8c9157d7bbea0bb96b0"
      url "https://github.com/xenforo-ltd/cli/releases/download/v#{version}/xf_linux_arm64.tar.gz"
      rename "xf_linux_arm64/bin/xf", "bin/xf"
    end
  end

  name "xf-cli"
  desc "Command line interface for XenForo"
  homepage "https://github.com/xenforo-ltd/cli"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "bin/xf"
  generate_completions_from_executable "bin/xf", "completion",
    shell_parameter_format: :cobra,
    shells: [:bash, :zsh, :fish, :pwsh]

  zap delete: [
      "~/Library/Caches/xf/",
      "~/.cache/xf/",
    ],
    trash: [
      "~/Library/Application Support/xf/",
      "~/.config/xf/",
    ]

end
