# This file was generated by GoReleaser. DO NOT EDIT.
cask "xf-cli" do
  version "0.1.7-alpha.7"

  on_macos do
    on_intel do
      sha256 "d65e49f3df755d1d808dd920100ec65c2468f603eb8878851d21ae9c27084555"
      url "https://github.com/xenforo-ltd/cli/releases/download/v#{version}/xf_macOS_amd64.tar.gz"
      rename "xf_macOS_amd64/bin/xf", "bin/xf"
    end
    on_arm do
      sha256 "bf40b211116a501fb38bf1cef2e91d4a61552b5deff3fa749ca23947fe3fe2d4"
      url "https://github.com/xenforo-ltd/cli/releases/download/v#{version}/xf_macOS_arm64.tar.gz"
      rename "xf_macOS_arm64/bin/xf", "bin/xf"
    end
  end

  on_linux do
    on_intel do
      sha256 "d13d4d721bc73fed5b3598de904ad9be3443ab3d780083456d15bb3fae87b018"
      url "https://github.com/xenforo-ltd/cli/releases/download/v#{version}/xf_linux_amd64.tar.gz"
      rename "xf_linux_amd64/bin/xf", "bin/xf"
    end
    on_arm do
      sha256 "897ab6e0bccf95717d8905ff9794dc0462f720d6e960f172cce93ab47c9f7ded"
      url "https://github.com/xenforo-ltd/cli/releases/download/v#{version}/xf_linux_arm64.tar.gz"
      rename "xf_linux_arm64/bin/xf", "bin/xf"
    end
  end

  name "xf-cli"
  desc "Command line interface for XenForo"
  homepage "https://github.com/xenforo-ltd/cli"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "bin/xf"

  zap delete: [
      "~/Library/Caches/xf/",
      "~/.cache/xf/",
    ],
    trash: [
      "~/Library/Application Support/xf/",
      "~/.config/xf/",
    ]

end
